### ISSUE TITLE
Change the Module name to fnbr.ts

### ISSUE THREAD

**Issue by Asphatire21** [fnbrjs/fnbr.js#114]
The module name does not fully compliment the language that the module is written in. In fact, only 1% of the module is JavaScript, while the rest 99% is TypeScript.

**Comment by ThisNils** [comment]
I thought about renaming the module too but decided against it. I think it would confuse people since the module can still be used with javascript and the only thing that changed in the npm version is that type definition files are being generated now. Also, I think you can't rename npm modules anyway, and making a new package could break existing projects using fnbr.js
